spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/master
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/slave1
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    call-setters-on-nulls: true
  mapper-locations: /mapper/*.xml