server:
  port: 8899

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/go?characterEncoding=utf-8&useSSL=false
      username: root
      password: mac666
      driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis配置
mybatis:
  configuration:
    call-setters-on-nulls: true
  mapper-locations: /mapper/*.xml