server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234567
    username: root

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.bulingfeng.entity
#showSql
logging:
  level:
    com:
      bulingfeng:
        mapper : debug